version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby

commands:
  setup:
    steps:
      # 実際はここにCircleCIのキャッシュの処理も入る
      - checkout
      - run: gem install bundler -v '2.0.1'
      - run: bundle install --path vendor/bundle

jobs:
  bundle:
    executor: default
    steps:
      - setup
      - persist_to_workspace:
          root: vendor
          paths:
            - bundle

  test:
    executor: default
    steps:
      - attach_workspace:
          at: vendor/bundle
      - setup
      - run: bundle exec rails test
  assets:
    executor: default
    steps:
      - attach_workspace:
          at: vendor/bundle
      - setup
      - run: bundle exec rails assets:precompile

workflows:
  all:
    jobs:
      - bundle
      - test:
          requires:
            - bundle
      - assets:
          requires:
            - bundle

