version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    environment:
      DISABLE_SPRING: true

commands:
  setup:
    steps:
      - checkout
      - run: gem install bundler -v '2.0.1'
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run: bundle install --path "vendor/bundle"
      - restore_cache:
          keys:
            - yarn-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-v1-{{ arch }}-{{ .Branch }}
            - yarn-cache-v1
      - run: yarn install

jobs:
  bundle:
    executor: default
    steps:
      - checkout
      - run: gem install bundler -v '2.0.1'
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - restore_cache:
          keys:
            - yarn-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-v1-{{ arch }}-{{ .Branch }}
            - yarn-cache-v1
      - run: bundle install --path "vendor/bundle" && bundle clean
      - run: yarn install
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: yarn-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules

  test:
    executor: default
    steps:
      - setup
      - run: bin/rails test
  assets:
    executor: default
    steps:
      - setup
      - run: bin/rails assets:precompile

workflows:
  all:
    jobs:
      - bundle
      - test:
          requires:
            - bundle
      - assets:
          requires:
            - bundle
