version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:latest-node-browsers

commands:
  setup:
    steps:
      - checkout
      - run: gem install bundler -v '2.0.1'
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run: bundle check || bundle install -j 4 --path vendor/bundle

jobs:
  bundle:
    executor: default
    steps:
      - checkout
      - run: gem install bundler -v '2.0.1'
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run: bundle install -j 4 --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle


  test:
    executor: default
    steps:
      - setup
      - run: bundle exec rails test
  assets:
    executor: default
    steps:
      - setup
      - run: bundle exec rails assets:precompile

workflows:
  all:
    jobs:
      - bundle
      - test:
          requires:
            - bundle
      - assets:
          requires:
            - bundle

